# Generated by Django 4.2.9 on 2024-02-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название уведомление')),
                ('text_positive', models.TextField(verbose_name='"Позитивный" текст уведомления')),
                ('text_negative', models.TextField(verbose_name='"Отрицательный" текст уведомления')),
                ('message_service', models.BooleanField(default=False, verbose_name='Личный кабинет на сервисе')),
                ('message_vk', models.BooleanField(default=False, verbose_name='Сообщение Вконтакте')),
                ('message_email', models.BooleanField(default=False, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Автоматическое уведомление',
                'verbose_name_plural': 'Автоматические уведомления',
            },
        ),
    ]
