# Generated by Django 4.2.9 on 2024-01-23 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('replenishment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('withdrawal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('community_count', models.PositiveIntegerField(default=0)),
                ('creative_count', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
