# Generated by Django 4.2.9 on 2024-02-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('replenishment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('withdrawal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('community_count', models.PositiveIntegerField(default=0)),
                ('creative_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
