# Generated by Django 4.2.9 on 2024-02-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='commission_replenishment',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=5),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='commission_withdrawal',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=5),
        ),
    ]
