# Generated by Django 4.2.9 on 2024-02-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0002_sitesettings_commission_replenishment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_income',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
    ]
