# Generated by Django 4.2.9 on 2024-03-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_statistics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
