# Generated by Django 4.2.9 on 2024-06-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historynotifications',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Файл для уведомления'),
        ),
        migrations.AlterField(
            model_name='historynotifications',
            name='UID',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='UID пользователя'),
        ),
    ]
