# Generated by Django 4.2.9 on 2024-05-28 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_remove_notification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=150, verbose_name='UID пользователя')),
                ('title', models.CharField(max_length=250, null=True, verbose_name='Тема уведомления')),
                ('text', models.TextField(verbose_name='Содержание уведомления')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('start', models.DateTimeField(blank=True, verbose_name='Дата отправки')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
