# Generated by Django 4.2.9 on 2024-05-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_historynotifications_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historynotifications',
            name='start',
        ),
    ]
