# Generated by Django 5.0.1 on 2024-01-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=150, unique=True, verbose_name='Рекламная ссылка')),
                ('name', models.CharField(max_length=150, verbose_name='Название ссылки')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Количество переходов')),
                ('registration_client', models.PositiveIntegerField(default=0, verbose_name='Количество зарегистрированных заказчиков')),
                ('registration_owner', models.PositiveIntegerField(default=0, verbose_name='Количество зарегистрированных владельцев')),
            ],
            options={
                'verbose_name': 'Рекламная ссылка',
                'verbose_name_plural': 'Рекламные ссылки',
            },
        ),
    ]
