# Generated by Django 5.0.1 on 2024-01-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetFullUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_user_id', models.IntegerField(unique=True, verbose_name='Уникальный полученный ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта пользователя')),
                ('account_vk', models.CharField(max_length=150, verbose_name='VK ID пользователя')),
                ('set_user_id', models.CharField(max_length=50, unique=True, verbose_name='Созданный специальный UID')),
            ],
            options={
                'verbose_name': 'Полученный пользователь',
                'verbose_name_plural': 'Полученные пользователи',
            },
        ),
    ]
