# Generated by Django 4.2.9 on 2024-02-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarningToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_service', models.BooleanField(default=False, verbose_name='Личный кабинет на сервисе')),
                ('message_vk', models.BooleanField(default=False, verbose_name='Сообщение Вконтакте')),
                ('message_email', models.BooleanField(default=False, verbose_name='Электронная почта')),
                ('text', models.TextField(verbose_name='Текст предупреждения')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата предупреждения')),
            ],
            options={
                'verbose_name': 'Отправка предупреждения',
                'verbose_name_plural': 'Отправка предупреждений',
            },
        ),
    ]
