# Generated by Django 5.0.1 on 2024-01-08 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_warnings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_service', models.BooleanField(default=False, verbose_name='Личный кабинет на сервисе')),
                ('message_vk', models.BooleanField(default=False, verbose_name='Сообщение Вконтакте')),
                ('message_email', models.BooleanField(default=False, verbose_name='Электронная почта')),
                ('text', models.TextField(verbose_name='Текст предупреждения')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата предупреждения')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_warnings.getfullusermodel', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отправка предупреждения',
                'verbose_name_plural': 'Отправка предупреждений',
            },
        ),
    ]
