# Generated by Django 5.0.1 on 2024-01-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_warnings', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=200, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
